### ISSUE TITLE
Error when infer

### ISSUE THREAD

**Issue by Quocvuong82** [b04901014/waveglow-tensorflow#1]
Traceback (most recent call last):
  File "/root/waveglow/model.py", line 172, in infer
    if self.load():
  File "/root/waveglow/model.py", line 145, in load
    self.saver.restore(self.sess, os.path.join(args.loading_path, ckpt_name))
AttributeError: 'WaveGlow' object has no attribute 'saver'
Traceback (most recent call last):
  File "main.py", line 34, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 31, in main
    model.infer()
  File "/root/waveglow/model.py", line 191, in infer
    for x in self.procs:
AttributeError: 'WaveGlow' object has no attribute 'procs'

**Comment by b04901014** [comment]
Now I've updated the code tested the inference, it should work in the latest version.

**Comment by Quocvuong82** [comment]
Thank you very much!
I tried inference on google colab but can not inference with the mel with time step ~ 800 -> 900 (~ 8s - 10s)

**Comment by b04901014** [comment]
What's the error message? I think it's the GPU out of memory? Since you feed a too long sequence for your GPU to afford. If it's the case, you can try to split the long utterance by silence and feed one sentence a time. Since it's plausible to have multiple sentences for 8s ~ 10s. Or you can just use a larger memory GPU.

**Comment by Quocvuong82** [comment]
Yes, this is GPU out of memory. But GPU on google colab ~11GB memory.
I'm trying split a mel by segment 256 time step -> OK.

**Comment by b04901014** [comment]
Yeah, since the memory requirement growths with the input segment length. The typical way is to feed one sentence a time. I think the sentence boundary can be determined from the energy of the mel spectrogram itself, but it may requires more coding. However, I'm not sure whether simply splitting into segments of 256 time step will cause audible artifacts at the discontinuities or not.

**Comment by Quocvuong82** [comment]
When training start (step 0):
W ./tensorflow/core/grappler/optimizers/graph_optimizer_stage.h:237] Failed to run optimizer ArithmeticOptimizer, stage HoistCommonFactor. Error: Node ArithmeticOptimizer/HoistCommonFactor_Add_add_24 is missing output properties at position :0 (num_outputs=0)
What it is?

**Comment by b04901014** [comment]
I receive the same warning, but it seems that it doesn't affect the training process.
Not sure what tensorflow operation caused such warning, but I think you can just ignore it.
I'm going to close this issue since the infer seems to function well.
If there are further side effects, please open a new issue to let me know.
